### ISSUE TITLE
Wireless connection to car

### ISSUE THREAD

**Issue by SusanLieu** [DIT112-V19/group-09#4]
## Description
As a home owner, I want to connect a laptop to the car so that I have access to the car.

## Acceptance Criteria
The Car will be connected to the computer using a bluetooth connection through a bluetooth module.

**Comment by SusanLieu** [comment]
As a home owner, I want to connect to the measuring device/car so that I can access the controls of the car.

As a home owner, I want to have access to the controls of the car so that I can measure a specific wall length.

**Comment by Natrix23** [comment]
Criterias:
-The Car will be connected to the computer using a bluetooth connection through a bluetooth module.
