### ISSUE TITLE
Automatically change direction

### ISSUE THREAD

**Issue by SusanLieu** [DIT112-V19/group-09#9]
## Description
As a real estate agent, I want the car to change directions when a wall is reached, so that it does not crash into the wall and damage the car itself.

## Acceptance Criteria
The car will be placed approximately 10cm from the starting point of the wall.
The sensor will detect a wall in time before the car collides with it.
The car will stop when an object is detected.
The car will automatically change direction once it's stopped and continue along the wall

**Comment by gusmikaja** [comment]
## Acceptance Criteria

The car will be placed approximately 10cm from the starting point of the wall.
The sensor will detect a wall in time before the car collides with it.
The car will stop when an object is detected.
The car will automatically change direction once it's stopped and continue along the wall

**Comment by mirunelle** [comment]
This is done.
